global:
  database:
    dbName: ${APPLICATION_GLOBAL_DB_NAME:jmpapp}
    dbSchema: ${APPLICATION_GLOBAL_DB_SCHEMA:public}
    sslMode: ${APPLICATION_GLOBAL_DB_SSL_MODE:disable}

spring:
  application:
    version: '@project.version@'
    name: jmp-app
  jmx:
    enabled: ${APPLICATION_JMX:false}
  mvc:
    log-request-details: true

  datasource:
    url: ${SPRING_DATASOURCE_JDBCURL:jdbc:postgresql://localhost:5432}/${global.database.dbName}?sslmode=${global.database.sslmode}
    username: ${SPRING_DATASOURCE_USERNAME:impuser}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: ${APPLICATION_DATABASE_CONNECTION_TIMEOUT:30000}
      maximum-pool-size: ${APPLICATION_DATABASE_MAXIMUM_POOL_SIZE:10}
      schema: ${global.database.dbSchema}

  jpa:
    properties:
      hibernate:
        default-schema: ${global.database.dbSchema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: ${APPLICATION_SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8

springdoc:
  packages-to-scan: com.epam
  swagger-ui:
    enabled: true
    operationsSorter: method
    tryItOutEnabled: true
    tagsSorter: alpha
    filter: true

management:
  monitoring:
    enabled: ${APPLICATION_MONITORING:true}
  health:
    mail:
      enabled: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    env:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,info,health,env,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: ${GLOBAL_LOGGING_LEVEL:INFO}
    org:
      springframework: ${logging.level.root:ERROR}
      hibernate: ${logging.level.root:ERROR}
      apache:
        tomcat: ${logging.level.root:INFO}
        catalina: ${logging.level.root:INFO}
    com:
      mkyong: ${logging.level.root:ERROR}
      root: ${logging.level.root:ERROR}