version: '3'
services:
  task-avro:
    container_name: task-avro
    image: task-avro
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APPLICATION_KAFKA_TASK_AVRO_TOPIC=task-avro-topic
      - APPLICATION_KAFKA_BOOTSTRAP_SERVERS=task-avro-kafka:9092
      - APPLICATION_KAFKA_GROUP_ID=task-avro-group
    depends_on:
      - task-avro-zookeeper
      - task-avro-kafka
    links:
      - task-avro-kafka
    restart: unless-stopped
    networks:
      - task-avro-net

  task-avro-zookeeper:
    image: wurstmeister/zookeeper
    container_name: task-avro-zookeeper
    ports:
      - "2181:2181"
    networks:
      - task-avro-net


  task-avro-kafka:
    image: confluentinc/cp-kafka:latest
    hostname: task-avro-kafka
    ports:
      - "9092:9092"
    depends_on:
      - task-avro-zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'task-avro-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://task-avro-kafka:9092,PLAINTEXT_INTERNAL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - task-avro-net

networks:
  task-avro-net:
    driver: bridge