version: '3'
services:
  task-avro:
    container_name: task-avro
    image: task-avro
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APPLICATION_KAFKA_TASK_AVRO_TOPIC=task-avro-topic
      - APPLICATION_KAFKA_BOOTSTRAP_SERVERS=task-avro-kafka:9092
      - APPLICATION_KAFKA_GROUP_ID=task-avro-group
      - APPLICATION_KAFKA_SCHEMA_REGISTRY= task-avro-schema-registry:8081
    depends_on:
      - task-avro-zookeeper
      - task-avro-kafka
    links:
      - task-avro-kafka
      - task-avro-schema-registry
    restart: unless-stopped
    networks:
      - task-avro-net

  task-avro-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: task-avro-schema-registry
    depends_on:
      - task-avro-zookeeper
      - task-avro-kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: task-avro-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'task-avro-zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://task-avro-schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://task-avro-kafka:9092,PLAINTEXT_INTERNAL://localhost:19092
      SCHEMA_REGISTRY_DEBUG: 'true'
    networks:
      - task-avro-net

  task-avro-zookeeper:
    image: wurstmeister/zookeeper
    container_name: task-avro-zookeeper
    ports:
      - "2181:2181"
    networks:
      - task-avro-net

  task-avro-kafka:
    image: confluentinc/cp-kafka:latest
    hostname: task-avro-kafka
    ports:
      - "9092:9092"
    depends_on:
      - task-avro-zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'task-avro-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://task-avro-kafka:9092,PLAINTEXT_INTERNAL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - task-avro-net

  task-avro-control-center:
    image: confluentinc/cp-enterprise-control-center:5.4.0
    hostname: task-avro-control-center
    container_name: task-avro-control-center
    depends_on:
      - task-avro-zookeeper
      - task-avro-kafka
      - task-avro-schema-registry
    ports:
      - "9021:9021"
    links:
      - task-avro-zookeeper
      - task-avro-kafka
      - task-avro-schema-registry
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'task-avro-kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'task-avro-zookeeper:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://task-avro-schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    restart: unless-stopped
    networks:
      - task-avro-net

networks:
  task-avro-net:
    driver: bridge